<?php
defined('BASEPATH') OR exit('No direct script access allowed');


/**
 * Met en place la liste définitive des fleurs
 * 
 */  
class Migration_Remove_latin_field extends CI_Migration {
    
    public function up() {
        // retire la colonne latin
        $this->dbforge->drop_column('fleurs', 'latin');
        
        
        // vide la table et ajoute les nouvelles fleurs
        $this->db->empty_table('fleurs');
        
        $query = "INSERT INTO `fj_fleurs` (`id`, `name_fr`, `name_en`) VALUES
(1, 'Ajania Silver And Gold', 'Ajania Silver And Gold'),
(2, 'Alpinia', 'Alpinia'),
(3, 'Alstroemeria', 'Alstroemeria'),
(4, 'Amaryllis', 'Amaryllis'),
(5, 'Ananas', 'Ananas'),
(6, 'Anemone', 'Anemone'),
(7, 'Oeuillet', 'Anje'),
(8, 'Anthurium', 'Anthurium'),
(9, 'Asclepias', 'Asclepias'),
(10, 'Asparagus', 'Asparagus'),
(11, 'Aster Blanc', 'Aster Wit'),
(12, 'Astilbe Rose  ', 'Astilbe Rose  '),
(13, 'Astrantia ', 'Astrantia '),
(14, 'Berkentak', 'Berkentak'),
(15, 'Bouvardia', 'Bouvardia'),
(16, 'Brassica', 'Brassica'),
(17, 'Bromelia', 'Bromelia'),
(18, 'Bupleurum Griffithii', 'Bupleurum Griffithii'),
(19, 'Calathea Green Ice', 'Calathea Green Ice'),
(20, 'Calla', 'Calla'),
(21, 'Cane Palm', 'Cane Palm'),
(22, 'Carthamus tinc. -', 'Carthamus tinc. overig'),
(23, 'Carthamus Zanzibar', 'Carthamus Zanzibar'),
(24, 'Chrysanthème', 'Chrysanthemum '),
(25, 'Clematis', 'Clematis'),
(26, 'Convall.', 'Convall.'),
(27, 'Cordeline', 'Cordeline'),
(28, 'Cotinus', 'Cotinus'),
(29, 'Craspedia', 'Craspedia'),
(30, 'Cyclamen', 'Cyclamen'),
(31, 'Cymbidium ', 'Cymbidium '),
(32, 'Genet cytissus', 'Cytisus Allgold (Heidelbeer)'),
(33, 'Aspidista', 'Aspedistra'),
(34, 'Beargras', 'Beargras'),
(35, 'Feuille de Chamaropses', 'Chamaropsesblad'),
(36, 'Feuille de Chico', 'Chico'),
(37, 'Cryptomeria', 'Cryptomeria'),
(38, 'Cupress', 'Cupress'),
(39, 'Cycas Revoluta', 'Cycas Revoluta'),
(40, 'Dracena', 'Dracena'),
(41, 'Feuille Euphorbe', 'Euphorbia'),
(42, 'Feuille de Galax ', 'Galax'),
(43, 'Kentia', 'Kentia'),
(44, 'Feuille de fougère Américaine', 'Lederblad'),
(45, 'Panicum Fountain', 'Panicum Fountain'),
(46, 'Papyrus (Bezem)', 'Papyrus (Bezem)'),
(47, 'Pittosporum ', 'Pittosporum '),
(48, 'Ruscus', 'Ruscus'),
(49, 'Salal', 'Salal'),
(50, 'Prêle', 'Dec.groen Speergras Bs.'),
(51, 'Speergras', 'Speergras'),
(52, 'Strelitzia', 'Strelitzia'),
(53, 'T-grass', 'T-grass'),
(54, 'Treeferm', 'Treevaren'),
(55, 'Typha', 'Typha'),
(56, 'Diplocyclos Palmatus', 'Diplocyclos Palmatus'),
(57, 'Oeuillet Green Trick', 'Duizendschoon Green Trick'),
(58, 'Feuille de chene', 'Eikenblad'),
(59, 'Eryngium ', 'Eryngium '),
(60, 'Eucalyptus', 'Eucalyptus'),
(61, 'Eucharis', 'Eucharis'),
(62, 'Eupatorium', 'Eupatorium'),
(63, 'Euphorbia', 'Euphorbia'),
(64, 'Flexigrass', 'Flexigrass'),
(65, 'Freesia', 'Freesia'),
(66, 'Gemberbollen', 'Gemberbollen'),
(67, 'Gerbera', 'Gerbera'),
(68, 'Germini', 'Germini'),
(69, 'Glaieul Blanc', 'Gladiool Wit'),
(70, 'Gomphrena', 'Gomphrena'),
(71, 'Grevillea', 'Grevillea'),
(72, 'Gyps Blanc  ', 'Gyps Wit  '),
(73, 'Gypsophila', 'Gypsophila'),
(74, 'Hedera', 'Hedera'),
(75, 'Tournesol ', 'Helianthus'),
(76, 'Heliconia', 'Hortensia '),
(77, 'Hortensia ', 'Hortensia '),
(78, 'Hypericum', 'Hypericum'),
(79, 'Ilex', 'Ilex'),
(80, 'Iris', 'Iris'),
(81, 'Cotton', 'Katoen'),
(82, 'Lys', 'Lelie'),
(83, 'Leucadendron', 'Leucadendron'),
(84, 'Leucospermum', 'Leucospermum'),
(85, 'Liatris', 'Liatris'),
(86, 'Lilly-gras', 'Lilly-gras'),
(87, 'Limonium', 'Limonium'),
(88, 'Livistona', 'Livistona'),
(89, 'Lotus', 'Livistona'),
(90, 'Lucky Bambou', 'Lucky Bambou'),
(91, 'Lisianthus', 'Lisianthus'),
(92, 'Matrecaria ', 'Matrecaria '),
(93, 'Mimosa', 'Mimosa'),
(94, 'Mitsumata', 'Mitsumata'),
(95, 'Molucella', 'Molucella'),
(96, 'Monstera', 'Monstera'),
(97, 'Musa ', 'Musa '),
(98, 'Myrtus', 'Myrtus'),
(99, 'Nerine', 'Nerine'),
(100, 'Orchidée', 'Orchid'),
(101, 'Dendrobium', 'Dendrobium'),
(102, 'Oncidium', 'Oncidium'),
(103, 'Phalaenopsis', 'Phalaenopsis'),
(104, 'Ornithogalum', 'Ornithogalum'),
(105, 'Pandanus', 'Pandanus'),
(106, 'Papaver ', 'Papaver '),
(107, 'Philo', 'Philo'),
(108, 'Pigface', 'Pigface'),
(109, 'Pine cone', 'Pine cone'),
(110, 'Pistachia ', 'Pistachia '),
(111, 'Populus  Robusta', 'Populus  Robusta'),
(112, 'Protea', 'Protea'),
(113, 'Renoncule', 'Buttercup'),
(114, 'Roebelini', 'Roebelini'),
(115, 'Rose Bellevue ', 'Rose Bellevue '),
(116, 'Rose Jaune ', 'Rose Geel '),
(117, 'Rose  A-1', 'Rose  A-1'),
(118, 'Rose  Ace Pink+', 'Rose  Ace Pink+'),
(119, 'Rose  Advance Sweetness', 'Rose  Advance Sweetness'),
(120, 'Rose  Akito', 'Rose  Akito'),
(121, 'Rose  Alchemy', 'Rose  Alchemy'),
(122, 'Rose  Alison', 'Rose  Alison'),
(123, 'Rose  All 4 Love+', 'Rose  All 4 Love+'),
(124, 'Rose  Amalia', 'Rose  Amalia'),
(125, 'Rose  Aqua Girl!', 'Rose  Aqua Girl!'),
(126, 'Rose  Aqua!', 'Rose  Aqua!'),
(127, 'Rose  Armando!', 'Rose  Armando!'),
(128, 'Rose  Artemis', 'Rose  Artemis'),
(129, 'Rose  Athena', 'Rose  Athena'),
(130, 'Rose  Avalanche+', 'Rose  Avalanche+'),
(131, 'Rose  Belle Rose', 'Rose  Belle Rose'),
(132, 'Rose  Bellevue', 'Rose  Bellevue'),
(133, 'Rose  Black Baccara', 'Rose  Black Baccara'),
(134, 'Rose  Blue Gene', 'Rose  Blue Gene'),
(135, 'Rose  Boheme', 'Rose  Boheme'),
(136, 'Rose  Burgundy', 'Rose  Burgundy'),
(137, 'Rose  Candlelight', 'Rose  Candlelight'),
(138, 'Rose  Catch!', 'Rose  Catch!'),
(139, 'Rose  Cézanne', 'Rose  Cézanne'),
(140, 'Rose  Cherry Brandy', 'Rose  Cherry Brandy'),
(141, 'Rose  Colandro', 'Rose  Colandro'),
(142, 'Rose  Cool Water!', 'Rose  Cool Water!'),
(143, 'Rose  Coral Reef', 'Rose  Coral Reef'),
(144, 'Rose  Cosima', 'Rose  Cosima'),
(145, 'Rose  Crème de la Crème', 'Rose  Crème de la Crème'),
(146, 'Rose  Cuba Gold', 'Rose  Cuba Gold'),
(147, 'Rose  Cuba Pink', 'Rose  Cuba Pink'),
(148, 'Rose  Dark Vampire!', 'Rose  Dark Vampire!'),
(149, 'Rose  Deep Eau', 'Rose  Deep Water'),
(150, 'Rose  Demetra', 'Rose  Demetra'),
(151, 'Rose  Dolce Vita+', 'Rose  Dolce Vita+'),
(152, 'Rose  Dolcetto!', 'Rose  Dolcetto!'),
(153, 'Rose  Dolomiti', 'Rose  Dolomiti'),
(154, 'Rose  Double Delight', 'Rose  Double Delight'),
(155, 'Rose  Downtown!', 'Rose  Downtown!'),
(156, 'Rose  Dreamland', 'Rose  Dreamland'),
(157, 'Rose  Duett', 'Rose  Duett'),
(158, 'Rose  El Toro', 'Rose  El Toro'),
(159, 'Rose  Eliza', 'Rose  Eliza'),
(160, 'Rose  Emotions', 'Rose  Emotions'),
(161, 'Rose  Equador Mix', 'Rose  Equador Mix'),
(162, 'Rose  Esperance', 'Rose  Esperance'),
(163, 'Rose  Espresso', 'Rose  Espresso'),
(164, 'Rose  F Red', 'Rose  F Red'),
(165, 'Rose  Feurio', 'Rose  Feurio'),
(166, 'Rose  Fiesta+', 'Rose  Fiesta+'),
(167, 'Rose  Florida', 'Rose  Florida'),
(168, 'Rose  Fragrant Delicious', 'Rose  Fragrant Delicious'),
(169, 'Rose  Free Spirit', 'Rose  Free Spirit'),
(170, 'Rose  Freedom', 'Rose  Freedom'),
(171, 'Rose  Furiosa', 'Rose  Furiosa'),
(172, 'Rose  Mixtes', 'Rose  Gemengd'),
(173, 'Rose  Gewaxt H%', 'Rose  Gewaxt H%'),
(174, 'Rose  Glamgirl', 'Rose  Glamgirl'),
(175, 'Rose  Glow dans the Dark', 'Rose  Glow in the Dark'),
(176, 'Rose  Glow!', 'Rose  Glow!'),
(177, 'Rose  Golden Ambition', 'Rose  Golden Ambition'),
(178, 'Rose  Good Times', 'Rose  Good Times'),
(179, 'Rose  Granada', 'Rose  Granada'),
(180, 'Rose  Grand Europe', 'Rose  Grand Europe'),
(181, 'Rose  Grand Prix', 'Rose  Grand Prix'),
(182, 'Rose  Green Fashion', 'Rose  Green Fashion'),
(183, 'Rose  H3O', 'Rose  H3O'),
(184, 'Rose  Harlequin', 'Rose  Harlequin'),
(185, 'Rose  Heaven!', 'Rose  Heaven!'),
(186, 'Rose  High & Candy', 'Rose  High & Candy'),
(187, 'Rose  High & Magic', 'Rose  High & Magic'),
(188, 'Rose  High & Orange Magic', 'Rose  High & Orange Magic'),
(189, 'Rose  High & Yellow Magic Fl.', 'Rose  High & Yellow Magic Fl.'),
(190, 'Rose  Hot Blood', 'Rose  Hot Blood'),
(191, 'Rose  Hot Merengue+', 'Rose  Hot Merengue+'),
(192, 'Rose  Ice Bear', 'Rose  Ice Bear'),
(193, 'Rose  Ilios!', 'Rose  Ilios!'),
(194, 'Rose  Impala', 'Rose  Impala'),
(195, 'Rose  Jumilia', 'Rose  Jumilia'),
(196, 'Rose  Keano', 'Rose  Keano'),
(197, 'Rose  Kiwi', 'Rose  Kiwi'),
(198, 'Rose  La Belle', 'Rose  La Belle'),
(199, 'Rose  Lenny', 'Rose  Lenny'),
(200, 'Rose  Lovely Dolomiti', 'Rose  Lovely Dolomiti'),
(201, 'Rose  Luxor', 'Rose  Luxor'),
(202, 'Rose  Magadi +', 'Rose  Magadi +'),
(203, 'Rose  Malibu', 'Rose  Malibu'),
(204, 'Rose  Mamamia', 'Rose  Mamamia'),
(205, 'Rose  Maracuja', 'Rose  Maracuja'),
(206, 'Rose  Marie-claire!', 'Rose  Marie-claire!'),
(207, 'Rose  Marina', 'Rose  Marina'),
(208, 'Rose  Mariyo!', 'Rose  Mariyo!'),
(209, 'Rose  Maroussia!', 'Rose  Maroussia!'),
(210, 'Rose  Masala', 'Rose  Masala'),
(211, 'Rose  Memory', 'Rose  Memory'),
(212, 'Rose  Memory Lane!', 'Rose  Memory Lane!'),
(213, 'Rose  Miss Piggy+', 'Rose  Miss Piggy+'),
(214, 'Rose  Mondial', 'Rose  Mondial'),
(215, 'Rose  Musette!', 'Rose  Musette!'),
(216, 'Rose  Myrna+', 'Rose  Myrna+'),
(217, 'Rose  N-Amour', 'Rose  N-Amour'),
(218, 'Rose  Naranga', 'Rose  Naranga'),
(219, 'Rose  Nicola', 'Rose  Nicola'),
(220, 'Rose  N-joy', 'Rose  N-joy'),
(221, 'Rose  Norma Jeane', 'Rose  Norma Jeane'),
(222, 'Rose  N-Tire', 'Rose  N-Tire'),
(223, 'Rose  Ocean Song', 'Rose  Ocean Song'),
(224, 'Rose  Olympia', 'Rose  Olympia'),
(225, 'Rose  Oops', 'Rose  Oops'),
(226, 'Rose  Orchestra', 'Rose  Orchestra'),
(227, 'Rose  Outlaw!', 'Rose  Outlaw!'),
(228, 'Rose  Pacific Blue', 'Rose  Pacific Blue'),
(229, 'Rose  Passion', 'Rose  Passion'),
(230, 'Rose  Pearl Avalanche+', 'Rose  Pearl Avalanche+'),
(231, 'Rose  Pebbles', 'Rose  Pebbles'),
(232, 'Rose  Penny Lane', 'Rose  Penny Lane'),
(233, 'Rose  Pink Finess', 'Rose  Pink Finess'),
(234, 'Rose  Pink Flame', 'Rose  Pink Flame'),
(235, 'Rose  Prestige', 'Rose  Prestige'),
(236, 'Rose  Prima Donna+', 'Rose  Prima Donna+'),
(237, 'Rose  Primaballerina', 'Rose  Primaballerina'),
(238, 'Rose  Pristine', 'Rose  Pristine'),
(239, 'Rose  Purple Power', 'Rose  Purple Power'),
(240, 'Rose  Red Desire', 'Rose  Red Desire'),
(241, 'Rose  Red Naomi!', 'Rose  Red Naomi!'),
(242, 'Rose  Red One', 'Rose  Red One'),
(243, 'Rose  Red Paris', 'Rose  Red Paris'),
(244, 'Rose  Red Ribbon', 'Rose  Red Ribbon'),
(245, 'Rose  Revival', 'Rose  Revival'),
(246, 'Rose  Revue', 'Rose  Revue'),
(247, 'Rose  Rosalie', 'Rose  Rosalie'),
(248, 'Rose  Rose L5', 'Rose  Rose L5'),
(249, 'Rose  Ruby Red', 'Rose  Ruby Red'),
(250, 'Rose  Salambo', 'Rose  Salambo'),
(251, 'Rose  Sanaa+', 'Rose  Sanaa+'),
(252, 'Rose  Savita+', 'Rose  Savita+'),
(253, 'Rose  Sombrero', 'Rose  Sombrero'),
(254, 'Rose  Sovereign', 'Rose  Sovereign'),
(255, 'Rose  Spotlight', 'Rose  Spotlight'),
(256, 'Rose  Sputnik!', 'Rose  Sputnik!'),
(257, 'Rose  Sudoku', 'Rose  Sudoku'),
(258, 'Rose  Sweet Akito', 'Rose  Sweet Akito'),
(259, 'Rose  Sweet Dolomiti', 'Rose  Sweet Dolomiti'),
(260, 'Rose  Tacazzi+', 'Rose  Tacazzi+'),
(261, 'Rose  Taiga', 'Rose  Taiga'),
(262, 'Rose  Talea+', 'Rose  Talea+'),
(263, 'Rose  Tenga Venga', 'Rose  Tenga Venga'),
(264, 'Rose  Testarossa', 'Rose  Testarossa'),
(265, 'Rose  Times Square', 'Rose  Times Square'),
(266, 'Rose  Tropical Amazone', 'Rose  Tropical Amazone'),
(267, 'Rose  Tropical Delight', 'Rose  Tropical Delight'),
(268, 'Rose  Tucan', 'Rose  Tucan'),
(269, 'Rose  Twin', 'Rose  Twin'),
(270, 'Rose  Upper Class', 'Rose  Upper Class'),
(271, 'Rose  Upper Secret', 'Rose  Upper Secret'),
(272, 'Rose  Vanilla Sky', 'Rose  Vanilla Sky'),
(273, 'Rose  Vendela', 'Rose  Vendela'),
(274, 'Rose  Vendela v.Blauw', 'Rose  Vendela v.Blauw'),
(275, 'Rose  Vuvuzela', 'Rose  Vuvuzela'),
(276, 'Rose  Wedding Bell', 'Rose  Wedding Bell'),
(277, 'Rose  Wham', 'Rose  Wham'),
(278, 'Rose  White Naomi!', 'Rose  White Naomi!'),
(279, 'Rose  White Rosalie', 'Rose  White Rosalie'),
(280, 'Rose  Wildfire', 'Rose  Wildfire'),
(281, 'Rose  Wimbledon', 'Rose  Wimbledon'),
(282, 'Rose  Zazu', 'Rose  Zazu'),
(283, 'Rose High & Magic ', 'Rose High & Magic '),
(284, 'Rose  Abrakadabra', 'Rose  Abrakadabra'),
(285, 'Rose  Antique Duett', 'Rose  Antique Duett'),
(286, 'Rose  Candid Prophyta', 'Rose  Candid Prophyta'),
(287, 'Rose  Sunwave', 'Rose  Sunwave'),
(288, 'Rose  Vampire!', 'Rose  Vampire!'),
(289, 'Rose  Viva!', 'Rose  Viva!'),
(290, 'Rose Orange ', 'Rose Orange '),
(291, 'Rose Jaune ', 'Rose Yellow '),
(292, 'Rose Rouge ', 'Rose Red '),
(293, 'Rose Rose ', 'Rose Rose '),
(294, 'Rose Branchus Avalanche Sorbet+', 'Rose Branchus Avalanche Sorbet+'),
(295, 'Rose Branchus Babe', 'Rose Branchus Babe'),
(296, 'Rose Branchus Barbados', 'Rose Branchus Barbados'),
(297, 'Rose Branchus Bombastic', 'Rose Branchus Bombastic'),
(298, 'Rose Branchus Cream Gracia', 'Rose Branchus Cream Gracia'),
(299, 'Rose Branchus Diadeem', 'Rose Branchus Diadeem'),
(300, 'Rose Branchus Dutch Dakar', 'Rose Branchus Dutch Dakar'),
(301, 'Rose Branchus Fire Flash', 'Rose Branchus Fire Flash'),
(302, 'Rose Branchus Gracia', 'Rose Branchus Gracia'),
(303, 'Rose Branchus Hot Bubbles', 'Rose Branchus Hot Bubbles'),
(304, 'Rose Branchus Isis', 'Rose Branchus Isis'),
(305, 'Rose Branchus Isis Classic!', 'Rose Branchus Isis Classic!'),
(306, 'Rose Branchus Lenne', 'Rose Branchus Lenne'),
(307, 'Rose Branchus Lovely Lydia', 'Rose Branchus Lovely Lydia'),
(308, 'Rose Branchus Mimi Eden', 'Rose Branchus Mimi Eden'),
(309, 'Rose Branchus Pink Irischka', 'Rose Branchus Pink Irischka'),
(310, 'Rose Branchus Purple Symphonie', 'Rose Branchus Purple Symphonie'),
(311, 'Rose Branchus Red Sensation', 'Rose Branchus Red Sensation'),
(312, 'Rose Branchus Rubicon', 'Rose Branchus Rubicon'),
(313, 'Rose Branchus Viviane !', 'Rose Branchus Viviane !'),
(314, 'Rose Branchus White Lady', 'Rose Branchus White Lady'),
(315, 'Rose Branchus Yellow Babe', 'Rose Branchus Yellow Babe'),
(316, 'Rose Tros. Avalanche+', 'Rose Branchus. Avalanche+'),
(317, 'Rose Blanche', 'Rose Wit '),
(318, 'Sandersonia', 'Sandersonia'),
(319, 'Sanseveria', 'Sanseveria'),
(320, 'Scabiosa Stellata', 'Scabiosa Stellata'),
(321, 'Skimmia', 'Skimmia'),
(322, 'Solidago', 'Solidago'),
(323, 'Solidaster', 'Solidaster'),
(324, 'Stillingia', 'Stillingia'),
(325, 'Strelitzia court', 'Strelitzia kort'),
(326, 'Stypha Pennata', 'Stypha Pennata'),
(327, 'Tige Salix (Katjes)', 'Tak Salix (Katjes)'),
(328, 'Thlaspi Green Bell', 'Thlaspi Green Bell'),
(329, 'Tilandsia Xeropgraphica', 'Tilandsia Xeropgraphica'),
(330, 'Ting Ting', 'Ting Ting'),
(331, 'Mini-oeuillet', 'Carnation'),
(332, 'Tulipe', 'Tulip'),
(333, 'Vanda Blue Magic', 'Vanda Blue Magic'),
(334, 'Veronica', 'Veronica'),
(335, 'Viburnum', 'Viburnum'),
(336, 'Waxappel', 'Waxappel'),
(337, 'Waxflower', 'Waxflower'),
(338, 'Waxpeer', 'Waxpeer');";  
        
        $this->db->query($query); 
    }
    
    public function down() {
        // remet la colonne "latin"     
        $field = array(
        
            'latin' => array(
                'type' => 'VARCHAR',
                'constraint' => '255',
                ),
        );        
        
        $this->dbforge->add_column('fleurs', $field);
        
    }
    
    
}